### PR TITLE
add warn/trip level to meter response

### PR DESCRIPTION
**Pull request by mstevetodd**
provides support for separate max vs trip levels

### CODE REVIEW

**Review by Asbelos — COMMENTED** [review]
I object to this on principle.. because its asking the overloaded and time critical  cs to do work that the jmri can do on a faster processor.

**Comment by mstevetodd** [comment]
> I object to this on principle.. because its asking the overloaded and time critical cs to do work that the jmri can do on a faster processor.

I'm sending one additional value, calculated once, for exactly the reason you mention, so that JMRI can do the work based on the value from the CS. What's the overload?

**Comment by Asbelos** [comment]
Sorry, i understood this was being sent as the result of a regular  poll request... On 18 Jan 2021 16:47, mstevetodd <notifications@github.com> wrote:

I object to this on principle.. because its asking the overloaded and time critical cs to do work that the jmri can do on a faster processor.

I'm sending one additional value, calculated once, for exactly the reason you mention, so that JMRI can do the work based on the value from the CS. What's the overload?

**Comment by mstevetodd** [comment]
> Sorry, i understood this was being sent as the result of a regular  poll request... 
It is sent as the response to the periodic 'c' request. Currently sent by JMRI every 10 seconds _only if_ the user has opened at least one Meter window. The maxmA and tripmA values are calculated only once, but _are_ sent in each message. If the extra bytes or the formatting in each message is an issue, I can change it to send only the name and value after the first time. JMRI is only creating the Meter from the full string once.

**Comment by Asbelos** [comment]
Caution .. Prog track trip level changes over time... 
A) powered on but not waiting for an ACK
B) Waiting for an ACK
C) Running a train with < 1 JOIN>

**Comment by FrightRisk** [comment]
I think we only care about main here, no? When we are programming, we assume 250mA, or the boosted value or 60mA over 250 (is that right), so we may want to know if what prog is set to as a check, but for normal monitoring, we mostly care about MAIN.

**Pull request merged**
