### PR TITLE
Added support for Teensy 3.2, 3.5, 3.6, 4.0 and 4.1

### PR DESCRIPTION
**Pull request by mjs513**
@Asbelos -@jakespeed1311 
This is basically where we left off with the other PR.  Had to redo github desktop to get everything in line.  
[Added Support for the Teensy 3.2, 3.5, 3.6, 4.0 and 4.1 MCUs](https://github.com/DCC-EX/CommandStation-EX/pull/125)

Note: Not ready to be merged but good for some testing.  Things need to get done:

1. changes to nointerrupts/interrupts in DCCWaveform
2. figure out what WDT is needed for?
3. wrap ifdefs for Teensy in DCCTimer - actually done.
4.  Analogread speed - need to test speed between mega and Teensies

Think there was something else but forgot.

Also have to figure this one out:
```
C:\Users\Merli\AppData\Local\Temp\arduino_build_954156\sketch\WiThrottle.cpp: In member function 'void WiThrottle::multithrottle(RingStream*, byte*)':
C:\Users\Merli\AppData\Local\Temp\arduino_build_954156\sketch\WiThrottle.cpp:229:49: warning: invalid conversion from 'void (*)(int)' to 'ACK_CALLBACK {aka void (*)(short int)}' [-fpermissive]
                   DCC::getLocoId(getLocoCallback); // will remove any previous join                    
                                                 ^
In file included from C:\Users\Merli\AppData\Local\Temp\arduino_build_954156\sketch\WiThrottle.cpp:44:0:
C:\Users\Merli\AppData\Local\Temp\arduino_build_954156\sketch\DCC.h:96:15: note:   initializing argument 1 of 'static void DCC::getLocoId(ACK_CALLBACK)'
   static void getLocoId(ACK_CALLBACK callback);
```
Still have to test a couple of the other boards.

### CODE REVIEW

**Comment by mjs513** [comment]
Tested basic functions on T4.1, T4.0, T3.6, T3.5 and T3.2.  By basic I mean WebThrottle can control the loco selected and <R 8 1 1> works as expected.  I think freemem is now working for Teensy but will retest T4.x tomorrow.  Getting SSD1306 display to test with as well.

T3.2 is failing for some reason - keeps indicating main track overload and <D> functions don't work.  Will play more tomorrow.

**Review by Asbelos — APPROVED** [review]
Will Update version to 3.0.10

**Comment by jakespeed1311** [comment]
HI,
you lost Teensy 4.1 Native Ethernet ! Or i am wrong ? 
Can you add this too please!
Jake

**Comment by mjs513** [comment]
It should be there - was about to test it but got sidetracked.  

All you should have to do is turn on ethernet in the config.  Unless it was disabled somewhere in the new code base.  I'll probably need another day or two before I can get back to it.

**Comment by mjs513** [comment]
@jakespeed1311 - @Asbelos 
I had to solder up a new ethernet cable and I enabled ethernet (don't uncomment IP address) and in serial monitor I see:
```
<* begin OK. *>
<* LCD4:IP: 192.168.1.252 *>
<* LCD5:Port:2560 *>
<* MotorDriver currentPin=A0, senseOffset=29, rawCurentTripValue(relative to offset)=668 *>
<* MotorDriver currentPin=A1, senseOffset=27, rawCurentTripValue(relative to offset)=668 *>
<* DCC-EX V-3.0.8 / TEENSY41 / STANDARD_MOTOR_SHIELD G-85a2b92 *>
<* Signal pin config: normal accuracy waveform *>
<* LCD1:Ready *>
<* LCD2:Free RAM=338902b *>
<* LCD2:Free RAM=338846b *>
```
If I do a arp -a  at the command prompt I see the address 192.168.1.252,   Just not sure how to test it yet.  I did install JMRI but haven't learned how to use it yet :)

**Comment by FrightRisk** [comment]
Well, depends how much you have implemented of our native functionality. That IP address looks like it connected to your router. Default is to install as an AP and the address is usually 192.168.4.1. Easiest way to test is to use a phone throttle like Engine Driver instead of JMRI. If you use JMRI, you are connecting the phone to their WiThrottle Server and they just send <DCC++> commands to us over the USB cable from the JMRI computer to the CS. If you load Engine Driver (Android) or WiThrottle (IOS) then you connect to the CS either as an AP or through the network, set the IP address and port in your phone app, and connect. That's it. Website has all the instructions here: https://dcc-ex.com/advanced-setup/wifi-config.html

**Comment by FrightRisk** [comment]
Well, you can test without JMRI. Just use your cell phone and the Engine Driver App (Android) or WiThrottle (IOS), enter the IP address and the port, and see if you can connect.

**Comment by mjs513** [comment]
Works with loconet and WiThrottle.

**Comment by mjs513** [comment]
Just a little more info on ethernet testing.  Yes it seems to be working but I did have an issue on disconnect and not sure if this is a Teensy problem or a App problem or something else.  If I use loconet it allows me to disconnect cleanly with a big button for disconnect and I don't see any issues.

WiThrottle - I can connect and control the loco with an issue. However I didn't see a clean way to disconnect so I just close the app and the Teensy hardfaulted but auto restarted (by design).  

jMRI.  I can see it connecting but not sure I am setting up the loco correctly because I can not get it to run - going to see if I can investigate more.

**Comment by FrightRisk** [comment]
If you need help, shout to UKBloke or SteveTodd. I haven't played with the WiThrottle interface.

**Pull request merged**
